version: '3'

services:
    app:
        image: app
        container_name: app
        ports:
            - 8000:8000
        depends_on:
            - db
        volumes:
            - .:/usr/src/
        command: bash -c "cd home/app/
            && alembic upgrade head
            && python3 app.py"

    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret_password
        volumes:
            - dbdata:/var/lib/postgresql/data/

volumes:
    dbdata: null