"""init

Revision ID: cfbd1092dd30
Revises: 
Create Date: 2024-10-01 11:50:32.111296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cfbd1092dd30"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "breeds",
        sa.Column(
            "breed_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("breed_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "cats",
        sa.Column("cat_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("color", sa.String(length=64), nullable=True),
        sa.Column("age_in_month", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("breed_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["breed_id"],
            ["breeds.breed_id"],
        ),
        sa.PrimaryKeyConstraint("cat_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cats")
    op.drop_table("breeds")
    # ### end Alembic commands ###
